services:
  - type: web
    name: lavalink-server
    env: docker
    plan: free
    healthCheckPath: /version
    envVars:
      - key: LAVALINK_PASSWORD
        generateValue: true
      - key: PORT
        value: 2333
